### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by za-wa-n-go** [WASasquatch/FreeU_Advanced#1]
There are many things, but what I would especially like to know is the purpose of these transfers.
Is it a challenge, an option with good results, or not?
Are there any particular theories?

bislerp 
colorize
cosine interp 
cuberp 
hslerp
inject 
lerp 
linear dodge

**Comment by za-wa-n-go** [comment]
In dinner_and_a_movie, switching multiscale_mode has no particular effect on the results.
All other parameters remain at default, only multiscale_mode is switched.

**Comment by WASasquatch** [comment]
> In dinner_and_a_movie, switching multiscale_mode has no particular effect on the results. All other parameters remain at default, only multiscale_mode is switched.

Do you have the scales overrided? Cause then those modes are skipped. 



> There are many things, but what I would especially like to know is the purpose of these transfers. Is it a challenge, an option with good results, or not? Are there any particular theories?
> 
> bislerp colorize cosine interp cuberp hslerp inject lerp linear dodge

No particular theory. It comes from the original FreeU, and how it's on the output blocks only, which means basically all the images will get burned out and too vibrant. So you can slerp back with original values, which produce new images not as tonally burned and drull. I left a couple other blending modes just for playing around with cause they change up result quite a bit. Some you have to use low strength with like 0.1

You'll notice if you switch to Input Blocks you get same similar added detail, without tonal burn and mass color change. I think because the model has more time to recover through middle and output blocks. 

***Example of Input versus Output blocks***
![image](https://github.com/WASasquatch/FreeU_Advanced/assets/1151589/46b2f1e3-296d-445e-afa3-044e56f8c48a)

***Example or Default multi-scale mode vs Sharpen and Multi-Sharpen*** Note: this is why I mention lowering blending modes or multi-scale strength for better results, this is with strengths at 1.0
![image](https://github.com/WASasquatch/FreeU_Advanced/assets/1151589/fc5d3985-a9c3-49db-874e-66ad210a0b36)

Here is an example image (and workflow attached) with strength turned down on mode:
![ComfyUI_00025_](https://github.com/WASasquatch/FreeU_Advanced/assets/1151589/def0b1c1-5b51-4e2e-8bfa-1104440c2a2b)

**Comment by WASasquatch** [comment]
Update: I did experience a scenario where the node was "dead" as far as the modes. I am not sure why, actually. I'm trying to figure it out. I restart and made a new node. I don't see anything that persists so not sure what it could be. It basically acts like it's stuck on "Default" which is `None` and no scales.

Edit: Starting to wonder if ComfyUI cache is bugged or something. Also experiencing similar with totally diff node and unrelated stuff, where the result isn't updated but the operation being done on it should be total change as it's entirely changing the conditioning for the prompt.

**Comment by za-wa-n-go** [comment]
>Do you have the scales overrided? 

No.
When I tried it with the workflow I received, it did indeed affect the appearance, so there must be something wrong with the way I put this workflow together.
Thanks.

**Comment by WASasquatch** [comment]
I do think there may be some caching issue. I just had another, issue with tolerance on a masking node not doing anything under I deleted and remade it. Something strange is going on 'round these parts lol. Could also be firefox, lately I have been having oddities like the loading browser not even connecting to the backend.

**Comment by za-wa-n-go** [comment]
Sorry, I'm not sure if I've misunderstood the specs or not.
I may have misunderstood the specs, but does the multiscale_mode result only work for output_blocks?

**Comment by WASasquatch** [comment]
> Sorry, I'm not sure if I've misunderstood the specs or not. I may have misunderstood the specs, but does the multiscale_mode result only work for output_blocks?

It should work for them all. Maybe there is a bug, but not that I can see.
